### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by rubberduck203** [rubberduck-vba/Rubberduck#2765]
Create an FAQ from the links referenced in #2762. 
These questions arise frequently and the info is all available, but doesn't seem to be quite visible enough. Then make it "big & visible".

- [ ] Create FAQ in the Wiki
- [ ] Add section in the ReadMe that links to it. 
- [ ] Add link to it in the website?
- [ ] Add it to the about dialog?

**Comment by Vogel612** [comment]
Not sure that the Repo Wiki is the right place for this. 

The repo wiki might be better off as "internal" documentation, with "user documentation" done on the Website... Opinions @rubberduck-vba/dev ?

**Comment by retailcoder** [comment]
There were talks of using xml-docs in the source code to generate the user documentation contents. I think that's the best way to do it. Needs quite a bit of work on the RD-Web repo then, and proper & complete xml-doc on all inspections, quickfixes, refactorings,... And basically all commands.
