### ISSUE TITLE
Package a PDF user manual along with the installer

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#317]
Not everyone downloading Rubberduck may venture into the depths of our GitHub repository, or even have Internet access on the computer they installed it on (use case: download setup.exe, copy to USB key, install on no-internet computer).
- [ ] Write a user manual
- [ ] Package it with the install, in PDF format
- [ ] Add shortcut to it in the start menu, under a "Rubberduck VBA" folder
- [x] While we're at it, add a shortcut to http://www.rubberduck-vba.com next to it

**Comment by ckuhn203** [comment]
Perhaps this is cheating, but can we just PDF the wiki? I can merge the individual files into one big PDF to distribute.

**Comment by ptwales** [comment]
Depending on what format the wiki source files are in, you can use [pandoc](http://johnmacfarlane.net/pandoc/) to easily translate the wiki to a PDF through LaTeX.  I have used it before and might be able to write a script to translate the wiki files to PDF.

**Comment by AndrewM-** [comment]
Ms-access is the domain of professionals who code not coding professionals so I think a manual is crucial.  I would hope that the rest of the community could assist the the manual (including myself), to keep the main team members free for development.

**Comment by PeterMTaylor** [comment]
I'm thinking of a balanced view of how to prepare RD  and steps to run a tests including samples provide for projects using RD (version) PDF titled "The Quackers guide to the VBA Galaxy!"
