### ISSUE TITLE
Add Search & Navigation to the Rubberduck commandbar

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#341]
Navigation is starting to become a major aspect of Rubberduck's features with v1.3 - let's add a navigation commandbar. I can think of a few useful buttons to put there:
- [x] Toggle _Code Explorer_
- [x] GoTo Anything #340
- [ ] Regex Search & Replace #327
- [x] Find all references #333 
- [x] Find all implementations #334

**Comment by Hosch250** [comment]
All of these are done an integrated except #327.  What's the plan for this?

**Comment by Vogel612** [comment]
I'm **pretty** sure that this can be closed 😅
