### ISSUE TITLE
Source Control Presenter Tests are a Mess

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#595]
- [x] [Extract `VerifyOffline` method](https://github.com/retailcoder/Rubberduck/blob/e630ea395c03755c6e9dc7e6ea2d06de23b653f9/RubberduckTests/SourceControl/SCPresenterTests.cs#L223-L225)
 - [x] Try moving Presenter Construction to TestInitialize
 - [x] [Extract method to verify child presenter's providers are not null.](https://github.com/retailcoder/Rubberduck/blob/e630ea395c03755c6e9dc7e6ea2d06de23b653f9/RubberduckTests/SourceControl/SCPresenterTests.cs#L497-L499). Some tests are [missing the settings presenter](https://github.com/retailcoder/Rubberduck/blob/e630ea395c03755c6e9dc7e6ea2d06de23b653f9/RubberduckTests/SourceControl/SCPresenterTests.cs#L297-L298). Getting this logic in one place will fix that.
