### ISSUE TITLE
Handle Procedure Attributes

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#786]
There are a number of opened issues that have been around since 0.x:
- [x] #52 toggle default instance attribute
- [x] #53 toggle default member attribute
- [x] #54 edit procedure description attribute
- [x] #55 toggle iterator getter attribute

2.0 is going to have to make them happen. I'm tagging with [code-parsing], but really this isn't about the parser - it's _purely_ about _parsing_: the VBE doesn't support member attributes, but honors them - this will be dirty string parsing work, without a net*; the VBE API can't help here.

*technically we could use the parser here, although I'm not sure how/whether it handles procedure attributes.

This feature will work off the current selection in the active code pane, and work when the selection is within a procedure:
- Export the code module to a temp file (don't remove it from the project just yet)
  - Find all procedure attributes
- Present the user with a modal UI to manage procedure attributes; allow user to cancel, or confirm changes.
- **If changes were made**: 
  - Remove the code module from the project
  - Insert the appropriate attributes and values where applicable
  - Save the temp file
  - Import the temp file back into the project

---

Default member attribute: there can only be one, implementation must validate that. Sets value `0` to attribute `VB_UserMemId`, where `[MemberName]` is the name of the member/procedure:

```
Attribute [MemberName].VB_UserMemId = 0
```

A default member should be a property getter. Given a `Text` property:

```
Dim foo As New Bar
foo.Text = "123"
```

Can turn into:

```
Dim foo As New Bar
foo = "123"
```

---

Iterator getter attribute: there can only be one, implementation must validate that. Sets value `-4` to attribute `VB_UserMemId`, on a `Property Get` member named `NewEnum`:

```
Attribute NewEnum.VB_UserMemId = -4
```

The feature could create the member if it doesn't exist, and prompt whether to remove it when it does and user is un-checking the box.

This member makes a type usable with a `For Each` loop, e.g. useful for a custom `List` class implementation.

---

Procedure description attribute: one per method, implementation must validate that. Displays a **short** description for the member when the module is viewed in the _Object Browser_:

```
Attribute [MemberName].VB_Description = "Short description of what the procedure does."
```

---

Default instance attribute is toggled in a class module's header:

```
Attribute VB_PredeclaredId = False
```

When set to `True`, VBA creates a _default instance_ of the class, which can then be accessed in a similar way to static classes in C# - instead of this:

```
Dim foo As New Bar
foo.DoSomething
```

You can now have that:

```
Bar.DoSomething
```

**Comment by retailcoder** [comment]
This could also be implemented the VB6 way:

![](http://i.stack.imgur.com/4W9OZ.png)

But that requires the user to know what `VB_UserMemId` values to use. I'd prefer to use checkboxes. Actually, the different `VB_UserMemId` values are mutually exlcusive, so they should be radiobuttons.

**Comment by ckuhn203** [comment]
All the ground work is laid, we just need someone to volunteer to implement it. I'm happy to guide someone in how to go about exporting/importing the code files.

**Comment by retailcoder** [comment]
Moving this to v2.1; for 2.0 we're going to be *reading* member and procedure attributes, and the resolver is making good use of them. *Writing* them is more work than we can fit into the 2.0 timeline.

**Comment by comintern** [comment]
Module attributes should probably be refactored to correspond with the [Instancing](https://msdn.microsoft.com/en-us/library/aa234184%28v=vs.60%29.aspx) property of the module. These are written in defined combinations.  This is described in [5.2.4.1.1](https://msdn.microsoft.com/en-us/library/ee177292.aspx) and [5.2.4.1.2](https://msdn.microsoft.com/en-us/library/ee199159.aspx) of the VB6 language spec.

They appear to set the following flags (although the VB6 ones need to be verified with a compiler):
```
Instancing		VB_Exposed	VB_Creatable	VB_GlobalNamespace	VB_PredeclaredId	MultiUse
Private			FALSE		FALSE		FALSE			FALSE			TRUE
PublicNotCreatable	TRUE		FALSE		FALSE			FALSE			TRUE
SingleUse		TRUE		TRUE		FALSE			TRUE			FALSE
GlobalSingleUse		TRUE		TRUE		TRUE			TRUE			FALSE
MultiUse		TRUE		TRUE		FALSE			FALSE			TRUE
GlobalMultiUse		TRUE		TRUE		TRUE			TRUE			TRUE
```

These attributes seem to correspond with the following [TYPEFLAGS](https://msdn.microsoft.com/en-us/library/windows/desktop/ms221509(v=vs.85).aspx):

VB_Creatable = TYPEFLAG_FCANCREATE
VB_Exposed = Unclear if these even make it to the tlb, but if they do - TYPEFLAG_FRESTRICTED
VB_GlobalNamespace = TYPEFLAGS.TYPEFLAG_FAPPOBJECT
VB_PredeclaredId = TYPEFLAG_FPREDECLID

In addition, the following attributes might make it easier to determine the type of document modules by examining the storage stream (see [MS-OVBA 3.1.3](https://msdn.microsoft.com/en-us/library/dd905966(v=office.12).aspx)):

VB_Base (Corresponds to GUID for parent class)
VB_TemplateDerived (Corresponds to TYPEFLAG_FAGGREGATABLE?)
VB_Customizable (Corresponds to !TYPEFLAG_FNONEXTENSIBLE)

It isn't clear if these are used in VB6 (need to test some compiles)

**Comment by rkapka** [comment]
Can someone tell me what is the state of this issue? I see that there are already annotation classes created for all the four attributes types. But apart from that, are these annotations actually doing anything?

If there's anything to be implemented, I would like to start with the procedure description.

**Comment by retailcoder** [comment]
@rkapka it's all pretty much done (in my fork), but I'm holding back on the final fixes because they require some tweaking to the parsing infrastructure, which aren't going to happen this close to a green release.

**Comment by rkapka** [comment]
@retailcoder Alrighty. I'll go check out something else, then. 😄
